config/routes.rb
Rails.application.routes.draw do

  #devise_for :users

  root 'pages#home'
  get '/players' => 'pages#players'
  get '/novo_jogo' => 'player_has_game#new_game'
  get '/add_players' => 'player_has_game#add_players'
  get '/show_games' => 'player_has_game#show'
  get '/edit_game' => 'player_has_game#edit_game'
  get '/view_games' => 'player_has_game#index'
  get '/post_edit' => 'player_has_game#edit_game_post'
  get '/admin' => 'pages#admin'
  get '/add_stadium' => 'stadia#new'
  get '/edit_stadium' => 'stadia#index'
  get '/edit_teams' => 'teams#index'
  get '/add_teams' => 'teams#new'

  devise_for :users
  #devise_for :sessions, controllers: {sessions: "users/sessions#new"}

  #resources :sessions
  resources :players
  resources :player_has_game
  resources :stadia
  resources :games
  resources :teams
  #resources :users


  match ':controller(/:action(/:id(.:format)))', via: [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  has_one :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartola.rb
class Cartola < ApplicationRecord
  belongs_to :user
  has_many :players, through: :cartola_players


end

app/models/cartola_player.rb
class CartolaPlayer < ApplicationRecord
  belongs_to :player
  belongs_to :cartola
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :players
end

app/models/player.rb
class Player < ApplicationRecord
  has_and_belongs_to_many :game
  belongs_to :team
  has_and_belongs_to_many :cartolas
  def unenrolled_cartolas
    Cartola.all - self.cartolas
  end

  def enrolled_in?(cartola)
    self.cartolas.include?(cartola)
  end

  def plays_in?(game)
    self.games.include?(game)
  end

  def not_playing_games
    Game.all - self.games
  end
end

app/models/player_has_game.rb
class PlayerHasGame < ApplicationRecord
  has_many :players
  has_many :games
end

app/models/round.rb
class Round < ApplicationRecord
end

app/models/stadium.rb
class Stadium < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players
  has_one :stadium
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def is_admin?
    self.admin
  end
end

app/controllers/stadia_controller.rb
class StadiaController < ApplicationController

  # GET /stadia
  # GET /stadia.json
  def index
    @stadia = Stadium.all
  end

  # GET /stadia/1
  # GET /stadia/1.json
  def show
    @stadia = Stadium.all
  end

  # GET /stadia/new
  def new
    @stadium = Stadium.new
  end

  # GET /stadia/1/edit
  def edit
  end

  # POST /stadia
  # POST /stadia.json
  def create
    @stadium = Stadium.new(stadium_params)

    respond_to do |format|
      if @stadium.save
        format.html { redirect_to @stadium, notice: 'Stadium was successfully created.' }
        format.json { render :show, status: :created, location: @stadium }
      else
        format.html { render :new }
        format.json { render json: @stadium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stadia/1
  # PATCH/PUT /stadia/1.json
  def update
    respond_to do |format|
      if @stadium.update(stadium_params)
        format.html { redirect_to @stadium, notice: 'Stadium was successfully updated.' }
        format.json { render :show, status: :ok, location: @stadium }
      else
        format.html { render :edit }
        format.json { render json: @stadium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stadia/1
  # DELETE /stadia/1.json
  def destroy
    @stadium.destroy
    respond_to do |format|
      format.html { redirect_to stadia_url, notice: 'Stadium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stadium
      @stadium = Stadium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stadium_params
      params.require(:stadium).permit(:city, :university, :cep, :street, :number, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartolas_helper.rb
module CartolasHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stadia_helper.rb
module StadiaHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/stadia/_form.html.erb
<%= form_for(stadium) do |f| %>
  <% if stadium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stadium.errors.count, "error") %> prohibited this stadium from being saved:</h2>

      <ul>
      <% stadium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :university %>
    <%= f.text_field :university %>
  </div>

  <div class="field">
    <%= f.label :cep %>
    <%= f.text_field :cep %>
  </div>

  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br/>
    <%= f.select :team_id, Team.all.order(:name).collect {|s| [(s.name), s.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stadia/edit.html.erb
<h1>Editing Stadium</h1>

<%= render 'form', stadium: @stadium %>

<%= link_to 'Show', @stadium %> |
<%= link_to 'Back', stadia_path %>

app/views/stadia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stadia</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>University</th>
      <th>Cep</th>
      <th>Street</th>
      <th>Number</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stadia.each do |stadium| %>
      <tr>
        <td><%= stadium.city %></td>
        <td><%= stadium.university %></td>
        <td><%= stadium.cep %></td>
        <td><%= stadium.street %></td>
        <td><%= stadium.number %></td>
        <td><%= stadium.state %></td>
        <td><%= link_to 'Show', stadium %></td>
        <td><%= link_to 'Edit', edit_stadium_path(stadium) %></td>
        <td><%= link_to 'Destroy', stadium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stadium', new_stadium_path %>

app/views/stadia/new.html.erb
<%= form_for @stadium do |f| %>

  <div class="form-group">
    <%= f.label :city %><br/>
    <%= f.text_field :city %>
  </div>

  <div class="form-group">
    <%= f.label :university %><br/>
    <%= f.text_field :university %>
  </div>

  <div class="form-group">
    <%= f.label :cep %><br/>
    <%= f.text_field :cep %>
  </div>

  <div class="form-group">
    <%= f.label :street %><br/>
    <%= f.text_field :street %>
  </div>

  <div class="form-group">
    <%= f.label :number %><br/>
    <%= f.text_field :number %>
  </div>

  <div class="form-group">
    <%= f.label :state %><br/>
    <%= f.text_field :state %>
  </div>

  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/stadia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @stadium.city %>
</p>

<p>
  <strong>University:</strong>
  <%= @stadium.university %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @stadium.cep %>
</p>

<p>
  <strong>Street:</strong>
  <%= @stadium.street %>
</p>

<p>
  <strong>Number:</strong>
  <%= @stadium.number %>
</p>

<p>
  <strong>State:</strong>
  <%= @stadium.state %>
</p>

<%= link_to 'Edit', edit_stadium_path(@stadium) %> |
<%= link_to 'Back', stadia_path %>