config/routes.rb
Rails.application.routes.draw do

  #devise_for :users

  root 'pages#home'
  get '/players' => 'pages#players'
  get '/novo_jogo' => 'player_has_game#new_game'
  get '/add_players' => 'player_has_game#add_players'
  get '/show_games' => 'player_has_game#show'
  get '/edit_game' => 'player_has_game#edit_game'
  get '/view_games' => 'player_has_game#index'
  get '/post_edit' => 'player_has_game#edit_game_post'
  get '/admin' => 'pages#admin'
  get '/add_stadium' => 'stadia#new'
  get '/edit_stadium' => 'stadia#index'
  get '/edit_teams' => 'teams#index'
  get '/add_teams' => 'teams#new'

  devise_for :users
  #devise_for :sessions, controllers: {sessions: "users/sessions#new"}

  #resources :sessions
  resources :players
  resources :player_has_game
  resources :stadia
  resources :games
  resources :teams
  #resources :users


  match ':controller(/:action(/:id(.:format)))', via: [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  has_one :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartola.rb
class Cartola < ApplicationRecord
  belongs_to :user
  has_many :players, through: :cartola_players


end

app/models/cartola_player.rb
class CartolaPlayer < ApplicationRecord
  belongs_to :player
  belongs_to :cartola
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :players
end

app/models/player.rb
class Player < ApplicationRecord
  has_and_belongs_to_many :game
  belongs_to :team
  has_and_belongs_to_many :cartolas
  def unenrolled_cartolas
    Cartola.all - self.cartolas
  end

  def enrolled_in?(cartola)
    self.cartolas.include?(cartola)
  end

  def plays_in?(game)
    self.games.include?(game)
  end

  def not_playing_games
    Game.all - self.games
  end
end

app/models/player_has_game.rb
class PlayerHasGame < ApplicationRecord
  has_many :players
  has_many :games
end

app/models/round.rb
class Round < ApplicationRecord
end

app/models/round_participation.rb
class RoundParticipation < ApplicationRecord
end

app/models/stadium.rb
class Stadium < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players
  has_one :stadium
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def is_admin?
    self.admin
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html {redirect_to @player, notice: 'Player was successfully created.'}
        format.json {render :show, status: :created, location: @player}
      else
        format.html {render :new}
        format.json {render json: @player.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html {redirect_to @player, notice: 'Player was successfully updated.'}
        format.json {render :show, status: :ok, location: @player}
      else
        format.html {render :edit}
        format.json {render json: @player.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html {redirect_to players_url, notice: 'Player was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  # GET /courses/1/cartolas
  def cartolas
    @player = Player.find(params[:id])
    @cartolas = @player.cartolas
  end

  def team
    @team = @player.teams
  end

  def name
    @name = @player.Name
  end
  def participates_in?(cartola)
    self.cartolas.include?(cartola)
  end

  def games(game)
    @player = Player.find(params[:id])
    teams = @player.teams
  end
  # POST /players/1/cartola_add?cartola_id=2
  def game_add
# Convert ids from routing to objects
    @player = Player.find(params[:id])
    game = Game.find(params[:game])

    if @player.plays_in?(game)
      flash[:error] = 'Player was already enrolled'
    else
      @player.games << @game
      flash[:notice] = 'Player was successfully enrolled'
    end
    redirect_to action: "games", id: @player
  end

  def game_remove
# Convert ids from routing to objects
    @player = Player.find(params[:id])
    game_ids = params[:games]
    if game_ids.any?
      game_ids.each do |game_id|
        game = Game.find(game_id)
        if @player.plays_in?(game)
          logger.info "Removing student from cartola #{game_id.id}"
          @player.games.delete(game)
          flash[:notice] = 'Cartola was successfully deleted'
          if game_ids.any?
            game_ids.each do |game_id|
              game = Game.find(game_id)
              if @player.plays_in?(game)
                logger.info "Removing student from cartola #{game.id}"
                @player.games.delete(game)
                flash[:notice] = 'Cartola was successfully deleted'
              end
            end
          end
          redirect_to action: "games", id: @player
        end
      end
    end
  end
  def cartola_add
# Convert ids from routing to objects
    @player = Player.find(params[:id])
    @cartola = Cartola.find(params[:cartola])

    if @player.enrolled_in?(@cartola)
      flash[:error] = 'Player was already enrolled'
    else
      @player.cartolas << @cartola
      flash[:notice] = 'Player was successfully enrolled'
    end
    redirect_to action: "cartolas", id: @player
  end

  def cartola_remove
# Convert ids from routing to objects
    @player = Player.find(params[:id])
    cartola_ids = params[:cartolas]
    if cartola_ids.any?
      cartola_ids.each do |cartola_id|
        cartola = Cartola.find(cartola_id)
        if @player.enrolled_in?(cartola)
          logger.info "Removing student from cartola #{cartola.id}"
          @player.cartolas.delete(cartola)
          flash[:notice] = 'Cartola was successfully deleted'
          if cartola_ids.any?
            cartola_ids.each do |cartola_id|
              cartola = Cartola.find(cartola_id)
              if @player.enrolled_in?(cartola)
                logger.info "Removing student from cartola #{cartola.id}"
                @player.cartolas.delete(cartola)
                flash[:notice] = 'Cartola was successfully deleted'
              end
            end
          end
          redirect_to action: "cartolas", id: @player
        end
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:Name, :Position, :team_id)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartolas_helper.rb
module CartolasHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stadia_helper.rb
module StadiaHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/players/_form.html.erb
<%= form_for(player) do |f| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %>
    <%= f.text_field :Name %>
  </div>

  <div class="field">
    <%= f.label :Position %><br>
    <%= f.select :Position, [['1st Base', '1B'],['2nd Base','2B'], ['3rd Base', '3B'], ['Shortstop', 'SS'], ['Pitcher', 'P'], ['Right Field', 'RF'], ['Center Field', 'CF'], ['Left Field', 'LF']] %>

  </div>

  <div class="field">
    <%= f.label :team_id %><br/>
    <%= f.select :team_id, Team.all.order(:name).collect {|s| [(s.name), s.id]} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/cartolas.html.erb
<h1><%= @player.Name %>'s cartolas</h1>
<% if @cartolas.length > 0 %>
  <%= form_tag(cartola_remove_player_path(@player)) do %>
    <table>
      <thead>
      <tr>
        <th>Cartola</th>
        <th>Remove</th>
      </tr>
      </thead>
      <tbody>
      <% for cartola in @cartolas do %>
        <tr>
          <td><%= cartola.nome %></td>
          <td><%= check_box_tag "cartolas[]", cartola.id %></td>
        </tr>
      <% end %></tbody>
    </table>
    <br/>
    <%= submit_tag 'Remove checked cartolas' %>
  <% end %>
<% else %>
  <p>Not enrolled in any cartolas yet.</p>
<% end %>
<h2>Enroll in new cartola</h2>
<% if @player.cartolas.count < Cartola.count then %>
  <%= form_tag(cartola_add_player_path(@player)) do %>
    <%= select_tag(:cartola, options_from_collection_for_select(
        @player.unenrolled_cartolas, :id, :nome)) %>
    <%= submit_tag 'Enroll' %>
  <% end %>
<% else %>
  <p><%= @player.Name %> is enrolled in every cartola.</p>
<% end %>
<p><%= link_to "Back", @player %></p>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Team</th>
      <th>Number of Cartolas></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.Name %></td>
        <td><%= player.Position %></td>
        <td><%= player.team.name %></td>
        <td><%= player.cartolas.count %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.Name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @player.Position %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>